# Generated by Django 3.0.3 on 2020-09-04 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shipping',
            new_name='ShippingAddress',
        ),
    ]
